### ISSUE TITLE
i want to stop my session and disconnect the socket?

### ISSUE THREAD

**Issue by MayurShiroya103** [fuwei007/OpenAIIOSRealtimeAPIDemo#1]
i want to stop my session and disconnect the socket?

**Comment by fuwei007** [comment]
@MayurShiroya103 
   Line 101 of SwftDemo/WebSocket/WebSocketManager.swift will remove the current buffer.

If you want to disconect the socket. You could use

WebSocketManager.shared.socket.disconnect()


Thanks

Frank

**Comment by MayurShiroya103** [comment]
@fuwei007 how to implement function calling inside voice to voice chat?

when i use WebSocketManager.shared.socket.disconnect() this method then going to .cancelled method not in .disconnected method.

and when i connect again then getting this error "Error: Optional(POSIXErrorCode(rawValue: 54): Connection reset by peer)" so please help me to resolve this issue

how to stop recording and clear data? and connect again

inshort, i want to to end session and when click on button again then again connect and working in well condition.

Thanks in advance :)

**Comment by fuwei007** [comment]
@MayurShiroya103 
   Sure. I will take a look this one. Regarding the function call you can take a look this video. https://youtu.be/G1ZNLPNHBcw?si=kTk77B7FiYOkJr8x 

For the function calling with realtime api. I am doing another video for that. Go ahead subscribe my youtube channel   https://www.youtube.com/@frankfu5460 You will get notification once I upload the video.

Thanks

Frank

**Comment by fuwei007** [comment]
@MayurShiroya103 
   I dig into more detail.
If you want to do what you said, 
1.first you should disconnect the WebSocket with the following code:
WebSocketManager.shared.socket.disconnect(closeCode: CloseCode.normal.rawValue)
2.Second, you will receive a message in the function:
func didReceive(event: WebSocketEvent, client: WebSocketClient) {
    // .cancelled for normal disconnection, 
    // .disconnected is shown for abnormal disconnection.
}
Inside this function, you should use the following code to stop audio playback:
PlayAudioContinuouslyManager.shared.audio_event_Queue.removeAll()
And to pause your audio capture engine, use:
RecordAudioManager.shared.pauseCaptureAudio()
3.The pauseCaptureAudio() function in PlayAudioContinuouslyManager.swift  is defined as:
func pauseCaptureAudio() {
    DispatchQueue.main.async {
        self.captureSession.stopRunning()
    }
}

Thanks

Frank

**Comment by MayurShiroya103** [comment]
@fuwei007 
func stopRecording() {
        // 1. Stop the Audio Unit
        if let audioUnit = audioUnit {
            AudioOutputUnitStop(audioUnit)
            AudioUnitUninitialize(audioUnit)
            self.audioUnit = nil
            print("Audio Unit stopped and uninitialized")
        }
        
        // 2. Clear the buffers and data arrays
        local_record_buffers.removeAll()
        local_record_Array.removeAll()
        count = 0
        print("Cleared local buffers and arrays")
        
        // 3. Reset audio session
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            do {
                let audioSession = AVAudioSession.sharedInstance()
                try audioSession.setActive(false, options: .notifyOthersOnDeactivation)
                print("Audio session deactivated")
                
                // 4. Disconnect the WebSocket
                WebSocketManager.shared.socket.disconnect()
                print("WebSocket disconnected")
            } catch {
                print("Failed to deactivate audio session: \(error)")
            }
        }
    }
    
    This code i have used for stop recording and disconnect the socket but while stop recording at that time getting below error 
    "Failed to deactivate audio session: Error Domain=NSOSStatusErrorDomain Code=560030580 "Session deactivation failed" UserInfo={NSLocalizedDescription=Session deactivation failed}"
    
    and again i am connecting socket and ask anything then audio not playing so please help me to resolve this issue?
    
    Thanks in advance!

**Comment by MayurShiroya103** [comment]
@fuwei007 if you have any solution then kindly please help me to resolve this issue.

**Comment by fuwei007** [comment]
@MayurShiroya103 
   Sure. I am looking into it.

Frank

**Comment by fuwei007** [comment]
@MayurShiroya103 
   I improved my code a little
![image](https://github.com/user-attachments/assets/705c2380-caeb-4752-9abf-5006bcd11832)


I am pushing the code.

**Comment by MayurShiroya103** [comment]
@fuwei007 Thanks for helping. it's working perfect. Do you have a demo of function calling with realtime open ai because i have tried but it's not getting perfect result so if you can help me then it will be good

i want to connect with my API like if i am asking about menu of breakfast then it will be check my api response and based on that they are giving match results

Thanks

**Comment by fuwei007** [comment]
@MayurShiroya103 
    Could you close this one and open another ticket for the function call. By the way I have the function calling implemented. I will update the video and push the code here.

Thanks

Frank
