### ISSUE TITLE
Realtime open ai with function calling

### ISSUE THREAD

**Issue by MayurShiroya103** [fuwei007/OpenAIIOSRealtimeAPIDemo#3]
@fuwei007 If you have implemented function calling with realtime open ai then kindly please help me to give code of function calling.

If user asking like what is menu for breakfast/dinner/lunch, etc. then it will be return data from my API calling so if you can help me to get results for this then help me.

Thanks in advance!

**Comment by fuwei007** [comment]
I have the python demo here for realtime api + function calling.https://youtu.be/rw3S7BbKh0o?si=oor7N-HjrYaQTBbu  I will appy to the iOS project later.
________________________________
From: MayurShiroya103 ***@***.***>
Sent: Wednesday, October 30, 2024 9:27:10 PM
To: fuwei007/OpenAIIOSRealtimeAPIDemo ***@***.***>
Cc: Frank Fu ***@***.***>; Mention ***@***.***>
Subject: [fuwei007/OpenAIIOSRealtimeAPIDemo] Realtime open ai with function calling (Issue #3)


@fuwei007<https://github.com/fuwei007> If you have implemented function calling with realtime open ai then kindly please help me to give code of function calling.

If user asking like what is menu for breakfast/dinner/lunch, etc. then it will be return data from my API calling so if you can help me to get results for this then help me.

Thanks in advance!

**Comment by fuwei007** [comment]
@MayurShiroya103 above video is help? If you still not get your issue fix I will update the swift code as well.

Thanks

Frank

**Comment by MayurShiroya103** [comment]
@fuwei007 no, if you can add code then it will be good for me

**Comment by MayurShiroya103** [comment]
[API.pdf](https://github.com/user-attachments/files/17627504/API.pdf)

@fuwei007 This is my pdf file of API response now the problem i have faced like

If i am asking "what is menu today?" then all menu list will be coming and audio play.

after if i asking about any product which is in API then give result of that product.

But while i am passing full response in below method then getting wrong result not accurate result

let sessionConfig: [String: Any] = [
            "type": "conversation.item.create",
            "item": [
                "type": "function_call_output",
                "call_id": call_id,
                "output": (full API response as a string)
            ]
        ]

So please let me know if anything wrong here so i will adjust it.

Thanks in advance!

**Comment by fuwei007** [comment]
@MayurShiroya103 
   I updated the code. You can see the function calling. For your case. You may not need use the function calling for this requirement.  You just give some prompt say "Your are an helper, Today the menu is .........". You can has the menu ready and tell the AI once you the session created.

Thanks

Frank
